os:
  windows:
    datapath: r'D:\01_Maanvi\LABB\datasets\kidney_dcecpc_TVT'
  ubuntu:
    datapath:
      /home/maanvi/LAB/Datasets/kidney_tumor_trainvaltest
  docker:
    datapath:
      /kw_resources/datasets/kidney_tumor_trainvaltest
currentos:
  docker
modelname:
      vgg
epochs:
  100
batch_size:
  16
learning_rate:
  0.001