data_options:
    train:
        batch_size: 8
        buffer_size: 1024
        output_size: [224, 224]
        slice_types: ['am','tm','dc','ec','pc']
        tumor_region_only: False
        aug_configs:
            random_crop:
            random_flip:
            random_contrast:
            random_warp:
    eval:
        batch_size: 64
        output_size: [224, 224]
        slice_types: ['am','tm','dc','ec','pc']
        tumor_region_only: False
