data_options:
    train:
        batch_size: 16
        buffer_size: 1024
        output_size: [224, 224]
        modalities: ['dc','pc','ec']
        tumor_region_only: True
        aug_configs:
            random_horizontalflip:
            
    eval:
        batch_size: 16
        output_size: [224, 224]
        modalities: ['dc','pc','ec']
        tumor_region_only: True
