data_options:
    modalities: ['am', 'dc', 'ec', 'pc', 'tm']
    cv: 5
    remote:
        data_path:
            /kw_resources/datasets/kt_new_trainvaltest
        save_path:
            /kw_resources/results/kidney_tumor/stacked830
    linux:
        data_path:
            /home/maanvi/LAB/Datasets/kt_new_trainvaltest
        save_path:
            /home/maanvi/LAB/results/kidney_tumor/stacked830
    windows:
        data_path:
            D:\01_Maanvi\LABB\datasets\kt_new_trainvaltest
        save_path:
            D:\01_Maanvi\LABB\results\kidney_tumor\stacked830
    train:
        batch_size: 32
        buffer_size: 1024
        output_size: [224, 224]
        tumor_region_only: True
        aug_configs:
            random_horizontalflip:
            random_verticalflip:
            random_rotation:
            random_brightness:
               
    eval:
        batch_size: 32
        output_size: [224, 224]
        tumor_region_only: True

    test:
        batch_size: 1
        output_size: [224, 224]
        tumor_region_only: True
